config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'customers#index'

  resources :customers
  resources :bill_books
  get 'export', to: 'customers#export'
  get 'search_customers', to: "customers#search"
  get 'search_employees', to: "employee_details#search"

  resources :employee_details

  resources :gcn_plans

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	mount_uploader :address_proof, AddressProofUploader
	mount_uploader :identity_proof, IdentityProofUploader
	belongs_to :employee_detail
	belongs_to :user
	has_one :payment_detail
	has_many :bill_books
	accepts_nested_attributes_for :bill_books
	accepts_nested_attributes_for :payment_detail
	accepts_nested_attributes_for :employee_detail

	validates :date, presence:true, length:{minimaum:3, maximum:25}
	validates :connection_id, presence:true, length:{minimaum:3, maximum:25}
	validates :name, presence:true, length:{minimaum:2, maximum:25}
	validates :mobile_no, presence:true, length:{minimaum:10, maximum:12}
	validates :email, presence:true, length:{minimaum:3, maximum:25}
	validates :telephone_no, presence:true, length:{minimaum:3, maximum:25}
	validates :date_of_birth, presence:true, length:{minimaum:3, maximum:25}
	validates :billing_address, presence:true, length:{minimaum:3, maximum:255}
	validates :pin_no, presence:true, length:{minimaum:2, maximum:25}
	validates :nationality, presence:true, length:{minimaum:3, maximum:25}
	validates :installation_address, presence:true, length:{minimaum:3, maximum:255}
	validates :installation_pin_no, presence:true, length:{minimaum:2, maximum:25}
	validates :installation_telephone_no, presence:true, length:{minimaum:2, maximum:15}
	validates :installation_mobile_no, presence:true, length:{minimaum:10, maximum:12}
	validates :installation_email, presence:true, length:{minimaum:2, maximum:25}
	validates :net_plan, presence:true, length:{minimaum:2, maximum:255}
	validates :address_proof, presence:true
	validates :address_proof_type, presence:true, length:{minimaum:2, maximum:25}
	validates :identity_proof, presence:true
	validates :identity_proof_type, presence:true, length:{minimaum:2, maximum:25}
	validates :identity_proof_no, presence:true, length:{minimaum:1, maximum:255}
	validates :address_proof_no, presence:true, length:{minimaum:1, maximum:255}

	def self.search(param)
	  return Customer.none if param.blank?

	  param.strip!
	  param.downcase!

	  (connection_id_matches(param) + name_matches(param) + email_matches(param) + mobile_no_matches(param) +telephone_no_matches(param)).uniq
	end

	def self.connection_id_matches(param)
	  matches('connection_id', param)
	end

	def self.name_matches(param)
	  matches('name', param)
	end

	def self.email_matches(param)
	  matches('email', param)
	end
	def self.mobile_no_matches(param)
	  matches('mobile_no', param)
	end
	def self.telephone_no_matches(param)
	  matches('telephone_no', param)
	end

	def self.matches(field_name, param)
	  where("lower(#{field_name}) like?","%#{param}%")
	end 
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def search
		@customer = Customer.search(params[:search_params])
		if @customer
			render partial: "look_up"
		else
			render status: not_found, nothing: true
		end
	end

	def index
		@customer = current_user.customers
		render layout: "custom"
	end

	def new
		@customer = Customer.new
		@customer.build_payment_detail
		@customer.bill_books.build
		render layout: "custom"
	end

	def create
		 # render plain: params[:customer][:employee_details][:emp_id]
		@customer = Customer.new(customer_params)
		@customer.user = current_user
		@customer.employee_detail = EmployeeDetail.where(emp_id: params[:customer][:employee_details][:emp_id]).take
		arr = params[:customer][:bill_books_attributes].map { |k, v| v["bill_amount"]}
		@customer.bill_books.each do |bill|
			bill.pending_bill = (params[:customer][:payment_detail_attributes][:total_amount].to_i - arr[0].to_i)
		end
		if @customer.save
			CustomerMailer.customer_confirmation(@customer).deliver
			flash[:success] = "Customer successfully created"
			redirect_to customers_path
		else
			render @customer
		end
	end

	def export
		
	end
	
	def show
		@customer = Customer.find(params[:id])
		@bill = BillBook.new()
		render layout: "customerdashbord"
	end

	private

	def customer_params
		params.require(:customer).permit(:date,:connection_id,:name,:mobile_no,:email,
			:telephone_no,:date_of_birth,:billing_address,:pin_no,:nationality,:installation_address,
			:installation_pin_no,:installation_telephone_no,:installation_mobile_no,:installation_email,
			:net_plan,:address_proof,:address_proof_type, :address_proof_no, :identity_proof,:identity_proof_type,:identity_proof_no,
			payment_detail_attributes: [:plan_cost, :plan_tax, :monthly_payment_cost,:id, :no_of_months_paid,
			:installation_charge, :company_material_use, :company_material_cost, :total_amount, :pending_amount ],
			bill_books_attributes: [:bill_book_date,:bill_book_no,:bill_no,:bill_amount, :bill_paid_by],employee_detail_ids: [])
	end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_look_up.html.erb
<div class="row" id="customer-main-block">
	<div class="col-md-12"  id="customer-seach-box">
		<div class="col-md-offset-3 col-md-6 custom-well">
			<%=form_tag search_customers_path, remote: true, method: :get, id: 'look-up-friend-form' do %>
			<div class="form-group look-up-friend col-md-7">
				<%= text_field_tag :search_params, params[:search_params], placeholder: 'Name, user id, email, mobile number', class: 'form-control input-lg', autofocus: true %>
			</div>
			<div class="form-group look-up-friend col-md-5">
				<%=button_tag(type: :submit, class: 'btn btn-lg btn-success look-sub-btn') do %>
					<span id="search-friend-cont"><i class="fa fa-search" aria-hidden="true"></i> Search</span>
					<span id="spin-lookup"><i class="fa fa-cog fa-spin fa-lg" aria-hidden="true"></i> Searching...</span>
				<% end %>
				<%= link_to '<i class="fa fa-times fa-lg" aria-hidden="true"></i>'.html_safe, customers_path, class: "btn btn-lg btn-danger close-lookup" %>
			</div>
			<% end %>
		</div>
		<div class="col-md-12">
			<hr/>
		</div>
	</div>	

<% if @customer %> 
	<% if @customer.size > 0 %>
		<div class="col-lg-12" id="customer-lookup-results">
			 <div class="table-responsive resp-table">
			  <table class="table table-striped customer-list-table">
			    <thead>
			      <tr class="danger">
			        <th>User Id</th>
			        <th>Employee Id</th>
			        <th>Date</th>
			        <th>name</th>
			        <th>Mobile no</th>
			        <th>Email</th>
			        <th>Telephone no</th>
			        <th>Nationality</th>
			        <th>Plan</th>
			        <th>Total amount</th>
			        <th>Pending amount</th>
			        <th>action</th>
			      </tr>
			    </thead>
			    <tbody>
			      <% @customer.each do |customer| %>
			        <tr>
			          <td><%= customer.connection_id %></td>
			          <td><%= customer.employee_detail.emp_id %></td>
			          <td><%= customer.date %></td>
			          <td><%= customer.name %></td>
			          <td><%= customer.mobile_no %></td>
			          <td><%= customer.email %></td>
			          <td><%= customer.telephone_no %></td>
			          <td><%= customer.nationality %></td>
			          <td><%= customer.net_plan %></td>
			          <td><%= customer.payment_detail.total_amount %></td>
			          <% customer.bill_books.each do |bill| %>
			            <% if bill == customer.bill_books.last%>
			              <td><%= bill.pending_bill.to_i%></td>
			            <% end %>
			      	  <% end %>
			          
			          <td><%=link_to 'See details', customer_path(customer), class: "btn btn-sm btn-success cust-see-detail-btn" %></td>
			        </tr>
			      <% end %>
			    </tbody>
			  </table>
			</div>
		</div>
	<% else %>
		<div class="col-lg-12">
			<p> No search criteria matches</p>	
		</div>
		
	<% end %>
<% end %>
<div class="col-md-12" id="lookup-errors"></div>
</div>

app/views/customers/export.html.erb
<div class="wrapper">
	<h1><span class="glyphicon glyphicon-share"></span> Export Customers</h1>
	<hr/>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <ul class="nav navbar-nav">
	      <li><%= link_to '<span class="glyphicon glyphicon-th-list"></span> List'.html_safe, customers_path %></li>
	      <li><%= link_to '<span class="glyphicon glyphicon-plus"></span> Add new'.html_safe, new_customer_path %></li>
	      <li class="active"><%= link_to '<span class="glyphicon glyphicon-share"></span> Export'.html_safe, export_path %></li>
	    </ul>
	  </div>
	</nav>
	<h1>Export page</h1>
</div>

app/views/customers/index.html.erb
<div class="wrapper">
  <div id="page-heading">
    <h1><span class="glyphicon glyphicon-th-list"></span> List of customers</h1>
    <hr/>
  </div>  
    
    <nav class="navbar navbar-default customer-navbar">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to '<span class="glyphicon glyphicon-th-list"></span> List'.html_safe, customers_path %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-plus"></span> Add new'.html_safe, new_customer_path %></li>
          <li><a id="search-item"><span class="glyphicon glyphicon-search"></span> Search</a></li>
        </ul>
      </div>
    </nav>
    <br/>
     <%= render 'look_up' %>
     
</div>