config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'customers#index'

  resources :customers
  resources :bill_books
  get 'export', to: 'customers#export'
  get 'search_customers', to: "customers#search"
  get 'search_employees', to: "employee_details#search"

  resources :employee_details

  resources :gcn_plans

end

app/models/gcn_plan.rb
class GcnPlan < ActiveRecord::Base
end

app/controllers/gcn_plans_controller.rb
class GcnPlansController < ApplicationController
  layout 'custom'

  def index
  	@plan = GcnPlan.all
  end

  def show
  end

  def new
  	@plan = GcnPlan.new
  end

  def create
	# render plain: params_plan
	@plan = GcnPlan.new(params_plan)

	if @plan.save
		flash[:success] = "Plan Successfully created"
		redirect_to gcn_plans_path

	else
		render 'new'
	end

  end


  private

  def params_plan
  	params.require(:gcn_plan).permit(:plan_name, :plan_price)
  end
end

app/helpers/gcn_plans_helper.rb
module GcnPlansHelper
end

app/views/gcn_plans/index.html.erb
<div class="wrapper">
  <div id="page-heading">
    <h1><span class="glyphicon glyphicon-th-list"></span> List of plans</h1>
    <hr/>
  </div>  
    
    <nav class="navbar navbar-default customer-navbar">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to '<span class="glyphicon glyphicon-th-list"></span> List'.html_safe, gcn_plans_path %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-plus"></span> Add new'.html_safe, new_gcn_plan_path %></li>
        </ul>
      </div>
    </nav>
    <br/>

    <div class="col-lg-6">
    	<div class="table-responsive resp-table">
    	  <table class="table table-striped bill-table">
    	    <thead>
    	      <tr class="danger">
    	        <th>No</th>
    	        <th>Plan</th>
    	        <th>Price</th>
    	      </tr>
    	    </thead>
    	    <tbody>
    	      <% @plan.each do |plan| %>
    	        <tr>
    	          <td><%= plan.id %></td>
    	          <td><%= plan.plan_name %></td>
    	          <td><i class="fa fa-inr" aria-hidden="true"></i> <%= plan.plan_price %></td>
    	        </tr>
    	      <% end %>
    	    </tbody>
    	  </table>
    	</div>
    </div>
</div>

app/views/gcn_plans/new.html.erb
<div class="wrapper">
  <div id="page-heading">
    <h1><span class="glyphicon glyphicon-th-list"></span> List of plans</h1>
    <hr/>
  </div>  
    
    <nav class="navbar navbar-default customer-navbar">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><%= link_to '<span class="glyphicon glyphicon-th-list"></span> List'.html_safe, gcn_plans_path %></li>
          <li class="active"><%= link_to '<span class="glyphicon glyphicon-plus"></span> Add new'.html_safe, new_customer_path %></li>
        </ul>
      </div>
    </nav>
    <br/>

    <div class="col-lg-6">
    	<%= form_for @plan do |f| %>
	    	<div class="form-group">
	    		<%= f.label :plan_name, "Plan" %>
	    		<%= f.text_field :plan_name, class: "form-control", placeholder: "Enter plan details" %>
	    	</div>
	    	<div class="form-group">
	    		<%= f.label :plan_price, "Price" %>
	    		<%= f.text_field :plan_price, class: "form-control", placeholder: "Enter plan price" %>
	    	</div>
	    	<div class="form-group">
	    		<%= f.submit class: "btn btn-md btn-danger" %>
	    	</div>
    	<% end %>
    </div>
</div>

app/views/gcn_plans/show.html.erb
<h1>GcnPlans#show</h1>
<p>Find me in app/views/gcn_plans/show.html.erb</p>