config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'customers#index'

  resources :customers
  resources :bill_books
  get 'export', to: 'customers#export'
  get 'search_customers', to: "customers#search"
  get 'search_employees', to: "employee_details#search"

  resources :employee_details

  resources :gcn_plans

end

app/models/employee_detail.rb
class EmployeeDetail < ActiveRecord::Base
	has_many :customers

	belongs_to :user

	validates :emp_id, presence:true, length:{minimaum:2, maximum:25}

	def self.search(param)
	  return EmployeeDetail.none if param.blank?

	  param.strip!
	  param.downcase!

	  (name_matches(param) + emp_id_matches(param)).uniq
	end

	def self.name_matches(param)
	  matches('name', param)
	end

	def self.emp_id_matches(param)
	  matches('emp_id', param)
	end

	def self.matches(field_name, param)
	  where("lower(#{field_name}) like?","%#{param}%")
	end 

end

app/controllers/employee_details_controller.rb
class EmployeeDetailsController < ApplicationController
  layout 'custom'
  

  def search
  	@employee = EmployeeDetail.search(params[:search_params])
  	if @employee
  		render partial: "look_up"
  	else
  		render status: not_found, nothing: true
  	end
  end

  def index
  	@employee = current_user.employee_details

  end

  def new
  	@employee = EmployeeDetail.new
  end

  def create
  	@employee = EmployeeDetail.new(employee_params)
  	@employee.user = current_user

  	if @employee.save
  		flash[:success] = "Employee successfully created"
  		redirect_to employee_details_path
  	else
  		flash[:success] = "Something went wrong"
  		render 'new'
  	end
  end

  def show
  end

  def edit
  end

  private
  def employee_params
  	params.require(:employee_detail).permit(:name, :emp_id)
  end

end

app/helpers/employee_details_helper.rb
module EmployeeDetailsHelper
end

app/views/employee_details/_look_up.html.erb
<div class="row" id="employee-main-block">
	<div class="col-md-12"  id="employee-seach-box">
		<div class="col-md-offset-3 col-md-6 custom-well">
			<%=form_tag search_employees_path, remote: true, method: :get, id: 'look-up-employee-form' do %>
			<div class="form-group look-up-friend col-md-7">
				<%= text_field_tag :search_params, params[:search_params], placeholder: 'Name, user id, email, mobile number', class: 'form-control input-lg', autofocus: true %>
			</div>
			<div class="form-group look-up-friend col-md-5">
				<%=button_tag(type: :submit, class: 'btn btn-lg btn-success look-sub-btn') do %>
					<span id="search-employee-cont"><i class="fa fa-search" aria-hidden="true"></i> Search</span>
					<span id="spin-employee-lookup"><i class="fa fa-cog fa-spin fa-lg" aria-hidden="true"></i> Searching...</span>
				<% end %>
				<%= link_to '<i class="fa fa-times fa-lg" aria-hidden="true"></i>'.html_safe, employee_details_path, class: "btn btn-lg btn-danger close-lookup" %>
			</div>
			<% end %>
		</div>
		<div class="col-md-12">
			<hr/>
		</div>
	</div>	

<% if @employee %> 
	<% if @employee.size > 0 %>
		<div class="col-lg-12" id="employee-lookup-results">
			 <div class="table-responsive resp-table">
			  <table class="table table-striped customer-list-table">
			    <thead>
			      <tr class="danger">
			        <th>User Id</th>
			        <th>Employee Id</th>
			        <th></th>
			      </tr>
			    </thead>
			    <tbody>
			      <% @employee.each do |employee| %>
			        <tr>
			          <td><%= employee.name %></td>
			          <td><%= employee.emp_id %></td>
			          <td><%=link_to 'See details', employee_detail_path(employee), class: "btn btn-sm btn-success cust-see-detail-btn" %></td>
			        </tr>
			      <% end %>
			    </tbody>
			  </table>
			</div>
		</div>
	<% else %>
		<div class="col-lg-12">
			<p> No search criteria matches</p>	
		</div>
		
	<% end %>
<% end %>
<div class="col-md-12" id="employee-lookup-errors"></div>
</div>

app/views/employee_details/edit.html.erb
<h1>EmployeeDetails#edit</h1>
<p>Find me in app/views/employee_details/edit.html.erb</p>

app/views/employee_details/index.html.erb
<div class="wrapper">
  <div id="page-heading">
    <h1><i class="fa fa-black-tie fa-lg" aria-hidden="true"></i> List of Executives</h1>
    <hr/>
  </div>  
    
    <nav class="navbar navbar-default customer-navbar">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to '<span class="glyphicon glyphicon-th-list"></span> List'.html_safe, employee_details_path %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-plus"></span> Add new'.html_safe, new_employee_detail_path   %></li>
          <li><a id="search-employee-item"><span class="glyphicon glyphicon-search"></span> Search</a></li>
        </ul>
      </div>
    </nav>
    <br/>
     <%= render 'look_up' %>
     
</div>

app/views/employee_details/new.html.erb
<div class="wrapper">
  <div id="page-heading">
    <h1><span class="glyphicon glyphicon-th-list"></span> Add New Employee</h1>
    <hr/>
  </div>  
    
    <nav class="navbar navbar-default customer-navbar">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><%= link_to '<span class="glyphicon glyphicon-th-list"></span> List'.html_safe, employee_details_path %></li>
          <li class="active"><%= link_to '<span class="glyphicon glyphicon-plus"></span> Add new'.html_safe, new_employee_detail_path   %></li>
        </ul>
      </div>
    </nav>
    
 
    <div class="row">
    	<div class="col-md-3">
    		<h3><b><span class="glyphicon glyphicon-user"></span> New customer</b></h3>
    		<hr/>

    		<%= form_for @employee do |f| %>
    			<div class="form-group">
    				<%= f.label :name, "Employee name" %>
    				<%= f.text_field :name, class: "form-control", placeholder: "Enter employee name" %>
    			</div>
    			<div class="form-group">
    				<%= f.label :emp_id, "Employee Id" %>
    				<%= f.text_field :emp_id, class: "form-control", placeholder: "Enter employee id." %>
    			</div>
    			<div class="form-group">
    				<%= f.submit "create employee", class: "btn btn-md btn-danger" %>
    			</div>
    		<% end %>
    	</div>
    </div>
</div>

app/views/employee_details/show.html.erb
<h1>EmployeeDetails#show</h1>
<p>Find me in app/views/employee_details/show.html.erb</p>