config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'customers#index'

  resources :customers
  resources :bill_books
  get 'export', to: 'customers#export'
  get 'search_customers', to: "customers#search"
  get 'search_employees', to: "employee_details#search"

  resources :employee_details

  resources :gcn_plans

end

app/views/layouts/_customerdashbordnavbar.html.erb
<nav class="navbar navbar-inverse customer-navbar">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to '<span class="glyphicon glyphicon-th-list"></span> List'.html_safe, customers_path %></li>
      <li><%= link_to '<span class="glyphicon glyphicon-plus"></span> Add new'.html_safe, new_customer_path %></li>
      <li><%= link_to '<span class="glyphicon glyphicon-share"></span> Export'.html_safe, customers_export_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top main-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><b><i>GCN Broadband</i></b></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to current_user.email %></li>
        <li><%= link_to '<span class="glyphicon glyphicon-off"></span> Log out'.html_safe, destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to '<span class="glyphicon glyphicon-log-in"></span> Login'.html_safe, new_user_session_path %></li>
      <% end %>  
    </ul>
  </div>
</nav>
<br/>
<br/>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gcnintraapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">

  <!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'> -->
  <link href="https://fonts.googleapis.com/css?family=Domine" rel="stylesheet" type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Rajdhani" rel="stylesheet" type='text/css'>


</head>
<body>
	<div  id="login-wrapper">
		<div class="container alert-box">
			<% flash.each do |name,msg| %>
				<div class="container animated bounceInDown">
					<div class="row">
						<div class="col-md-offset-3 col-md-6">
							<div class="alert alert-dismissible alert-<%= "#{name}" %>">
							  <button type="button" class="close" data-dismiss="alert"><span class="glyphicon glyphicon-remove-circle"></span></button>
							  <b><%= msg %></b>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>

		<%= yield %>
	</div>
</body>
</html>

app/views/layouts/custom.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gcnintraapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">

  <!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'> -->
  <link href="https://fonts.googleapis.com/css?family=Domine" rel="stylesheet" type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Rajdhani" rel="stylesheet" type='text/css'>


</head>
<body>
	
	<div class="container alert-box">
		<% flash.each do |name,msg| %>
			<div class="container animated bounceInDown">
				<div class="row">
					<div class="col-md-offset-3 col-md-6">
						<div class="alert alert-dismissible alert-<%= "#{name}" %>">
						  <button type="button" class="close" data-dismiss="alert"><span class="glyphicon glyphicon-remove-circle"></span></button>
						  <b><%= msg %></b>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
	<div class="container-fluid">

		<div class="row">
			<div class="col-lg-2 side-bar">
				<%= link_to image_tag("aboutimg.png", :border=>0, class: "img-responsive logo-img" ), root_path, :alt=>"logo"  %>
				<ul class="nav sidebar-nav">
				  <li class="active"><%=link_to '<i class="fa fa-users" aria-hidden="true"></i> Customers'.html_safe, customers_path %></li>
				  <li><%=link_to '<i class="fa fa-black-tie fa-lg" aria-hidden="true"></i> Executives'.html_safe, employee_details_path %></li>
				  <li><%=link_to '<i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i> Plans'.html_safe, gcn_plans_path %></li>

				</ul>
			</div>
			<div class="col-sm-11 col-lg-10 col-md-10 side-bar-contet" style="float:right">
				<%= render 'layouts/navbar' %>
				<%= yield %>
		  	</div>
		</div>
		
	</div>
</body>
</html>

app/views/layouts/customerdashbord.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gcnintraapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">

  <link href="https://fonts.googleapis.com/css?family=Domine" rel="stylesheet" type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Rajdhani" rel="stylesheet" type='text/css'>
</head>
<body class="home" style="background-color: #F5F5F5">
	<div class="container alert-box">
		<% flash.each do |name,msg| %>
			<div class="container animated bounceInDown">
				<div class="row">
					<div class="col-md-offset-3 col-md-6">
						<div class="alert alert-dismissible alert-<%= "#{name}" %>">
						  <button type="button" class="close" data-dismiss="alert"><span class="glyphicon glyphicon-remove-circle"></span></button>
						  <b><%= msg %></b>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
	<%= yield %>
</body>
</html>